title: Tenny cooks
description: > # this means to ignore newlines until "baseurl:"
  Collection of Tenny's recipes and food pictures.
permalink: ':title/'
baseurl: "/tennycooks" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tenny # add your name
author-img: tennycooks2.jpg # add your photo
about-author: Cooking is a therapeutic, creative outlet for me, which is why I rarely follow recipes exactly. All recipes and pictures posted here are my own.
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 30
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
